backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "static/images/uploads" # The src attribute for uploaded media will begin with static/images/uploads

collections:
  - name: "workouts"
    label: "Workouts"
    format: "json"
    create: true,
    files:
      - label: "Workouts Page"
        name: "workouts"
        file: "static/content/workouts.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Start Date", name: "start_date", widget: "datetime" }
          - { label: "End Date", name: "end_date", widget: "datetime" }
          - { label: "Featured Image", name: "image", widget: "image" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body Copy", name: "body", widget: "markdown" }